name: Deploy via SSM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSM
        uses: aws-actions/aws-ssm-run-command@v1
        with:
          instance-ids: ${{ secrets.EC2_INSTANCE_ID }}  # e.g., i-0abcdef12345
          document-name: AWS-RunShellScript
          comment: Deploy Express App
          parameters: |
            commands:
              - cd /home/ubuntu/todo-backend
              - git pull 
              - npm install 
              - pm2 restart all
        env:
          AWS_REGION: ap-south-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
