name: Deploy to EC2 via SSM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: Execute SSM Command
        run: |
          aws ssm send-command \
            --region ap-south-1 \
            --document-name "AWS-RunShellScript" \
            --targets '[{"Key":"InstanceIds","Values":["i-0ecdbcec92dcf5786"]}]' \
            --parameters 'commands=["cd /home/ubuntu/todo-backend && git pull origin main && npm install && pm2 restart all"]' \
            --comment "Auto deploy via SSM" \
            --query "Command.CommandId" \
            --output text
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
