name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6   
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/todo-backend
            git pull 
            touch .env
            echo "${{ secrets.ENV }}" > .env
            npm install
            pm2 restart all
            pm2 save
            pm2 list
