name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.4.0 
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/todo-backend
            git pull origin main
            touch .env
            echo "${{ secrets.ENV }}" > .env
            npm install
            pm2 restart your-app-name
